// epk.js - Dynamically loads images for the EPK page

document.addEventListener("DOMContentLoaded", () => {
    // epkImages is defined in epk_images.js (generated by generate_image_list.sh)
    if (typeof epkImages === 'undefined' || !epkImages.length) {
        console.error("No images found or epk_images.js is missing.");
        return;
    }

    const sliderContainer = document.getElementById('epk-slider');
    const galleryContainer = document.getElementById('epk-gallery');
    
    // Filter to ensure we only render images
    const validImages = epkImages.filter(img => img.match(/\.(jpg|jpeg|png|webp|gif)$/i));

    if (validImages.length === 0) return;

    const slides = [];

    validImages.forEach((imgName, index) => {
        // 1. Populate Slider
        const slide = document.createElement('div');
        slide.className = 'epk-slide';
        if (index === 0) slide.classList.add('active');
        slide.style.backgroundImage = `url('assets/epk/${imgName}')`;
        if (sliderContainer) {
            sliderContainer.appendChild(slide);
            slides.push(slide);
        }

        // 2. Populate Gallery
        const galleryItem = document.createElement('div');
        galleryItem.className = 'epk-masonry-item';
        
        const imgEl = document.createElement('img');
        imgEl.src = `assets/epk/${imgName}`;
        imgEl.alt = "SFIMP EPK Gallery Image";
        imgEl.loading = "lazy"; // Add lazy loading for performance
        
        galleryItem.appendChild(imgEl);
        if (galleryContainer) {
            galleryContainer.appendChild(galleryItem);
        }
    });

    if (slides.length > 1) {
        let currentIndex = 0;
        setInterval(() => {
            slides[currentIndex].classList.remove('active');
            currentIndex = (currentIndex + 1) % slides.length;
            slides[currentIndex].classList.add('active');
        }, 5000);
    }
});

// Render YouTube videos from statically generated youtubeVideos array
function initEPKVideos() {
    const epkVideosContainer = document.querySelector('.epk-videos');
    if (!epkVideosContainer || typeof youtubeVideos === 'undefined') return;

    if (youtubeVideos.length > 0) {
        epkVideosContainer.innerHTML = youtubeVideos.map((video) => {
            const title = video.title.replace(/"/g, '&quot;');
            return `
                <div class="epk-video-card">
                    <div class="epk-video-wrapper">
                        <iframe src="https://www.youtube.com/embed/${video.id}" title="${title}" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            `;
        }).join('');
    }
}

document.addEventListener('DOMContentLoaded', initEPKVideos);
